<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>patterns</key>
	<array>
		<!-- gcc style (-vbr) errors -->
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([\/]+.*):([0-9]+):([0-9]+): (?:error|fatal|warning|hint)+: (.*)$</string>
			<key>name</key>
			<string>meta.error.conosle.pascal</string>
		</dict>
		<!-- project stats -->
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\* (\w+) ('.*')$</string>
			<key>name</key>
			<string>meta.message.conosle.pascal</string>
		</dict>
		<!-- [messages] -->
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\[(.*)\]$</string>
			<key>name</key>
			<string>meta.message.conosle.pascal</string>
		</dict>
	</array>
	<key>name</key>
	<string>FPC Console</string>
	<key>uuid</key>
	<string>39F338E1-C2A5-41F4-8DE4-949ECD7A87C3</string>
</dict>
</plist>