
[variables]

  PRODUCT_NAME = '${program-name}'

[settings]

  configuration = "debug"
  unitPaths = ['./sources',
               ]
  libraryPaths = []

  compiler = "/usr/local/lib/fpc/${LATEST}/${ARCH}"
  program = "./sources/${PRODUCT_NAME}.pas"
  output = './output'
  executable = "./${PRODUCT_NAME}"
  options = ["-vbr"]

[configuration.debug]

  options = ["-gw", "-godwarfcpp", "-Sa"]

[configuration.release]

  options = ["-Xs", "-O2"]

[platforms.darwin]
  
  options = ["-WP10.10"]
